Repository han-sy/intern-2020, pull requests merged in 2020-02, with the labels that each got.

#89 Bootstrap modal
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/ajax/functionAjax.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/event/functionEvent.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: improvement

#91 부트스트랩 댓글 답글 적용하기
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: bug, improvement

#94 handlebar 따로 빼기 + 버튼 디자인 및 댓글 디자인 수정
  blockboard/src/main/resources/static/css/boardstyle.css
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: improvement

#98 search option태그의 value수정
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: feedback

#103 controller, mapper, service 위치정리
  blockboard/src/main/java/com/board/project/blockboard/controller/BoardController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/MainController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/BoardMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/CompanyMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/UserMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/BoardService.java
  blockboard/src/main/java/com/board/project/blockboard/service/CompanyService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/java/com/board/project/blockboard/service/UserService.java
  blockboard/src/main/resources/mybatis/mapper/BoardMapper.xml
  blockboard/src/main/resources/mybatis/mapper/CompanyMapper.xml
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/mybatis/mapper/UserMapper.xml
  blockboard/src/main/resources/mybatis/mybatis-config.xml
  blockboard/src/main/resources/static/js/ajax/postAjax.js
Labels: improvement

#126 불필요한 주석 제거
  blockboard/src/main/java/com/board/project/blockboard/controller/BoardController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/CommentController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/FunctionController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/MainController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/ReplyController.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/java/com/board/project/blockboard/service/ReplyService.java
  blockboard/src/main/java/com/board/project/blockboard/service/UserService.java
Labels: feedback

#130 기능 변경 리팩토링
  blockboard/build.gradle
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/common/util/CompareData.java
  blockboard/src/main/java/com/board/project/blockboard/common/util/JsonParse.java
  blockboard/src/main/java/com/board/project/blockboard/controller/BoardController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/FunctionController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/FunctionDTO.java
  blockboard/src/main/java/com/board/project/blockboard/service/FunctionService.java
  blockboard/src/main/resources/mybatis/mapper/FunctionMapper.xml
  blockboard/src/main/resources/static/js/ajax/functionAjax.js
  blockboard/src/main/resources/static/js/event/functionEvent.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: feedback

#127 constant.js 생성하여 상수 관리 - COMMENT_PREFIX.length 추가
  blockboard/build.gradle
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/common/util/CompareData.java
  blockboard/src/main/java/com/board/project/blockboard/common/util/JsonParse.java
  blockboard/src/main/java/com/board/project/blockboard/controller/BoardController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/FunctionController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/FunctionDTO.java
  blockboard/src/main/java/com/board/project/blockboard/service/FunctionService.java
  blockboard/src/main/resources/mybatis/mapper/FunctionMapper.xml
  blockboard/src/main/resources/static/js/ajax/functionAjax.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/event/functionEvent.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/resources/static/js/util/constant.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: feedback

#124 json parsing 할수 있는 static method 생성. stringToMapArrayList 추가
  blockboard/build.gradle
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/common/util/CompareData.java
  blockboard/src/main/java/com/board/project/blockboard/common/util/JsonParse.java
  blockboard/src/main/java/com/board/project/blockboard/controller/BoardController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/CommentController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/FunctionController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/MainController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/ReplyController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/FunctionDTO.java
  blockboard/src/main/java/com/board/project/blockboard/service/FunctionService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/java/com/board/project/blockboard/service/ReplyService.java
  blockboard/src/main/java/com/board/project/blockboard/service/UserService.java
  blockboard/src/main/resources/mybatis/mapper/FunctionMapper.xml
  blockboard/src/main/resources/static/js/ajax/functionAjax.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/event/functionEvent.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/resources/static/js/util/constant.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: feedback

#131 게시글 작성/수정 시 input length 검사
  blockboard/src/main/java/com/board/project/blockboard/common/util/LengthCheckUtils.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/resources/static/js/event/common.js
  blockboard/src/main/resources/static/js/event/postEvent.js
Labels: feedback, improvement

#123 mybatis 검색 조건문 수정
  blockboard/src/main/java/com/board/project/blockboard/common/util/LengthCheckUtils.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/resources/mybatis/mapper/CompanyMapper.xml
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/static/js/event/common.js
  blockboard/src/main/resources/static/js/event/postEvent.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: feedback

#151 Jsoup을 이용한 HTML Parse
  blockboard/build.gradle
  blockboard/src/main/java/com/board/project/blockboard/common/util/HTMLTagUtils.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
Labels: improvement

#160 인기게시글 목록 조회
  blockboard/src/main/java/com/board/project/blockboard/common/exception/GlobalExceptionHandler.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/PostDTO.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/static/js/ajax/postAjax.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/updateUI/boardUI.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: enhancement

#156 기능변경정보 List<FunctionDTO> 로 받아오기
  blockboard/src/main/java/com/board/project/blockboard/common/exception/GlobalExceptionHandler.java
  blockboard/src/main/java/com/board/project/blockboard/controller/FunctionController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/FunctionDTO.java
  blockboard/src/main/java/com/board/project/blockboard/dto/PostDTO.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/FunctionService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/static/js/ajax/functionAjax.js
  blockboard/src/main/resources/static/js/ajax/postAjax.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/event/functionEvent.js
  blockboard/src/main/resources/static/js/updateUI/boardUI.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: feedback

#154 댓글수 조회 + 게시글 조회수
  Database/table_create.sql
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/common/exception/GlobalExceptionHandler.java
  blockboard/src/main/java/com/board/project/blockboard/controller/CommentController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/FunctionController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PostController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/ReplyController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/FunctionDTO.java
  blockboard/src/main/java/com/board/project/blockboard/dto/PostDTO.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/CommentMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/FunctionMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/CommentService.java
  blockboard/src/main/java/com/board/project/blockboard/service/FunctionService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/resources/mybatis/mapper/CommentMapper.xml
  blockboard/src/main/resources/mybatis/mapper/FunctionMapper.xml
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/ajax/functionAjax.js
  blockboard/src/main/resources/static/js/ajax/postAjax.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/event/functionEvent.js
  blockboard/src/main/resources/static/js/updateUI/boardUI.js
  blockboard/src/main/resources/static/js/updateUI/functionUI.js
  blockboard/src/main/resources/static/js/updateUI/paginationUI.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: enhancement

#187 답글 자동 태그, 댓글/답글 에디터 수정
  Database/table_create.sql
  blockboard/src/main/java/com/board/project/blockboard/controller/ReplyController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/CommentDTO.java
  blockboard/src/main/java/com/board/project/blockboard/service/CommentService.java
  blockboard/src/main/java/com/board/project/blockboard/service/ReplyService.java
  blockboard/src/main/resources/mybatis/mapper/AlarmMapper.xml
  blockboard/src/main/resources/mybatis/mapper/CommentMapper.xml
  blockboard/src/main/resources/mybatis/mapper/ReplyMapper.xml
  blockboard/src/main/resources/static/ckeditor/plugins/mentions/plugin.js
  blockboard/src/main/resources/static/css/boardstyle.css
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/updateUI/alarmUI.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: bug, improvement

#188 Feature/function check upgrade
  Database/table_create.sql
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/service/FileService.java
  blockboard/src/main/resources/static/ckeditor/config.js
  blockboard/src/main/resources/static/ckeditor/plugins/filetools/plugin.js
  blockboard/src/main/resources/static/css/boardstyle.css
  blockboard/src/main/resources/static/css/loginstyle.css
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/ajax/postAjax.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/event/functionEvent.js
  blockboard/src/main/resources/static/js/event/postEvent.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/resources/static/js/updateUI/functionUI.js
  blockboard/src/main/resources/static/js/updateUI/postUI.js
  blockboard/src/main/resources/static/js/util/data.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: improvement

#204 스티커 페이징 적용
  blockboard/src/main/java/com/board/project/blockboard/controller/StickerController.java
  blockboard/src/main/java/com/board/project/blockboard/service/StickerService.java
  blockboard/src/main/resources/static/ckeditor/plugins/emoji/icons/next.png
  blockboard/src/main/resources/static/ckeditor/plugins/emoji/icons/prev.png
  blockboard/src/main/resources/static/ckeditor/plugins/emoji/plugin.js
  blockboard/src/main/resources/static/ckeditor/plugins/emoji/skins/default.css
Labels: improvement

#208 Sticker 전면 리팩토링 & sessionStorage 저장
  blockboard/src/main/java/com/board/project/blockboard/controller/StickerController.java
  blockboard/src/main/java/com/board/project/blockboard/service/StickerService.java
  blockboard/src/main/resources/static/ckeditor/plugins/emoji/plugin.js
Labels: improvement

#209 회원 추가 시 검증
  blockboard/src/main/java/com/board/project/blockboard/common/exception/GlobalExceptionHandler.java
  blockboard/src/main/java/com/board/project/blockboard/controller/UserController.java
  blockboard/src/main/java/com/board/project/blockboard/service/UserService.java
  blockboard/src/main/resources/static/js/ajax/userAjax.js
  blockboard/src/main/resources/static/js/event/common.js
  blockboard/src/main/resources/static/js/event/userEvent.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
  blockboard/src/test/java/com/board/project/blockboard/ModuleTest.java
Labels: bug, improvement

#210 알람 클릭 시 처리
  Database/table_create.sql
  blockboard/src/main/java/com/board/project/blockboard/common/exception/GlobalExceptionHandler.java
  blockboard/src/main/java/com/board/project/blockboard/common/interceptor/JwtInterceptor.java
  blockboard/src/main/java/com/board/project/blockboard/controller/AlarmController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/CommentController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/AlarmDTO.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/AlarmMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/CommentMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/AlarmService.java
  blockboard/src/main/java/com/board/project/blockboard/service/CommentService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/resources/mybatis/mapper/AlarmMapper.xml
  blockboard/src/main/resources/mybatis/mapper/CommentMapper.xml
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/static/css/alarmstyle.css
  blockboard/src/main/resources/static/css/boardstyle.css
  blockboard/src/main/resources/static/js/ajax/alarmAjax.js
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/ajax/fileAjax.js
  blockboard/src/main/resources/static/js/event/alarmEvent.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/updateUI/alarmUI.js
  blockboard/src/main/resources/static/js/updateUI/boardUI.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: enhancement

#211 댓글답글 카운트& 페이징
  Database/table_create.sql
  blockboard/src/main/java/com/board/project/blockboard/common/config/WebConfig.java
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/controller/CommentController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PaginationController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/ReplyController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/CommentDTO.java
  blockboard/src/main/java/com/board/project/blockboard/dto/PaginationDTO.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/CommentMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/ReplyMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/CommentService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PaginationService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/java/com/board/project/blockboard/service/ReplyService.java
  blockboard/src/main/resources/mybatis/mapper/CommentMapper.xml
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/mybatis/mapper/ReplyMapper.xml
  blockboard/src/main/resources/static/ckeditor/plugins/filetools/plugin.js
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/ajax/fileAjax.js
  blockboard/src/main/resources/static/js/ajax/paginationAjax.js
  blockboard/src/main/resources/static/js/ajax/postAjax.js
  blockboard/src/main/resources/static/js/data/boardData.js
  blockboard/src/main/resources/static/js/data/commentData.js
  blockboard/src/main/resources/static/js/data/const.js
  blockboard/src/main/resources/static/js/data/functionData.js
  blockboard/src/main/resources/static/js/data/postData.js
  blockboard/src/main/resources/static/js/data/userData.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/event/common.js
  blockboard/src/main/resources/static/js/event/fileEvent.js
  blockboard/src/main/resources/static/js/event/paginationEvent.js
  blockboard/src/main/resources/static/js/event/postEvent.js
  blockboard/src/main/resources/static/js/updateUI/boardUI.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/resources/static/js/updateUI/fileUI.js
  blockboard/src/main/resources/static/js/updateUI/functionUI.js
  blockboard/src/main/resources/static/js/updateUI/paginationUI.js
  blockboard/src/main/resources/static/js/updateUI/postUI.js
  blockboard/src/main/resources/static/js/util/data.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/resources/static/js/util/windowLoad.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
Labels: improvement

#207 모달창 스크롤바 추가
  Database/table_create.sql
  blockboard/src/main/java/com/board/project/blockboard/common/config/WebConfig.java
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/common/exception/GlobalExceptionHandler.java
  blockboard/src/main/java/com/board/project/blockboard/controller/CommentController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PaginationController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/ReplyController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/UserController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/CommentDTO.java
  blockboard/src/main/java/com/board/project/blockboard/dto/PaginationDTO.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/CommentMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/ReplyMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/CommentService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PaginationService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/java/com/board/project/blockboard/service/ReplyService.java
  blockboard/src/main/java/com/board/project/blockboard/service/UserService.java
  blockboard/src/main/resources/mybatis/mapper/CommentMapper.xml
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/mybatis/mapper/ReplyMapper.xml
  blockboard/src/main/resources/static/ckeditor/plugins/filetools/plugin.js
  blockboard/src/main/resources/static/css/boardstyle.css
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/ajax/fileAjax.js
  blockboard/src/main/resources/static/js/ajax/paginationAjax.js
  blockboard/src/main/resources/static/js/ajax/postAjax.js
  blockboard/src/main/resources/static/js/ajax/userAjax.js
  blockboard/src/main/resources/static/js/data/boardData.js
  blockboard/src/main/resources/static/js/data/commentData.js
  blockboard/src/main/resources/static/js/data/const.js
  blockboard/src/main/resources/static/js/data/functionData.js
  blockboard/src/main/resources/static/js/data/postData.js
  blockboard/src/main/resources/static/js/data/userData.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/event/common.js
  blockboard/src/main/resources/static/js/event/fileEvent.js
  blockboard/src/main/resources/static/js/event/modalEvent.js
  blockboard/src/main/resources/static/js/event/paginationEvent.js
  blockboard/src/main/resources/static/js/event/postEvent.js
  blockboard/src/main/resources/static/js/event/userEvent.js
  blockboard/src/main/resources/static/js/updateUI/boardUI.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/resources/static/js/updateUI/fileUI.js
  blockboard/src/main/resources/static/js/updateUI/functionUI.js
  blockboard/src/main/resources/static/js/updateUI/paginationUI.js
  blockboard/src/main/resources/static/js/updateUI/postUI.js
  blockboard/src/main/resources/static/js/util/data.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/resources/static/js/util/windowLoad.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
  blockboard/src/test/java/com/board/project/blockboard/ModuleTest.java
Labels: improvement

#206 모달창 우선순위 제어
  Database/table_create.sql
  blockboard/src/main/java/com/board/project/blockboard/common/config/WebConfig.java
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/common/exception/GlobalExceptionHandler.java
  blockboard/src/main/java/com/board/project/blockboard/controller/CommentController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/PaginationController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/ReplyController.java
  blockboard/src/main/java/com/board/project/blockboard/controller/UserController.java
  blockboard/src/main/java/com/board/project/blockboard/dto/CommentDTO.java
  blockboard/src/main/java/com/board/project/blockboard/dto/PaginationDTO.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/CommentMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/PostMapper.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/ReplyMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/CommentService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PaginationService.java
  blockboard/src/main/java/com/board/project/blockboard/service/PostService.java
  blockboard/src/main/java/com/board/project/blockboard/service/ReplyService.java
  blockboard/src/main/java/com/board/project/blockboard/service/UserService.java
  blockboard/src/main/resources/mybatis/mapper/CommentMapper.xml
  blockboard/src/main/resources/mybatis/mapper/PostMapper.xml
  blockboard/src/main/resources/mybatis/mapper/ReplyMapper.xml
  blockboard/src/main/resources/static/ckeditor/plugins/filetools/plugin.js
  blockboard/src/main/resources/static/css/boardstyle.css
  blockboard/src/main/resources/static/js/ajax/boardAjax.js
  blockboard/src/main/resources/static/js/ajax/commentAjax.js
  blockboard/src/main/resources/static/js/ajax/fileAjax.js
  blockboard/src/main/resources/static/js/ajax/paginationAjax.js
  blockboard/src/main/resources/static/js/ajax/postAjax.js
  blockboard/src/main/resources/static/js/ajax/userAjax.js
  blockboard/src/main/resources/static/js/data/boardData.js
  blockboard/src/main/resources/static/js/data/commentData.js
  blockboard/src/main/resources/static/js/data/const.js
  blockboard/src/main/resources/static/js/data/functionData.js
  blockboard/src/main/resources/static/js/data/postData.js
  blockboard/src/main/resources/static/js/data/userData.js
  blockboard/src/main/resources/static/js/event/boardEvent.js
  blockboard/src/main/resources/static/js/event/commentEvent.js
  blockboard/src/main/resources/static/js/event/common.js
  blockboard/src/main/resources/static/js/event/fileEvent.js
  blockboard/src/main/resources/static/js/event/modalEvent.js
  blockboard/src/main/resources/static/js/event/paginationEvent.js
  blockboard/src/main/resources/static/js/event/postEvent.js
  blockboard/src/main/resources/static/js/event/userEvent.js
  blockboard/src/main/resources/static/js/updateUI/boardUI.js
  blockboard/src/main/resources/static/js/updateUI/commentUI.js
  blockboard/src/main/resources/static/js/updateUI/fileUI.js
  blockboard/src/main/resources/static/js/updateUI/functionUI.js
  blockboard/src/main/resources/static/js/updateUI/paginationUI.js
  blockboard/src/main/resources/static/js/updateUI/postUI.js
  blockboard/src/main/resources/static/js/util/data.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/resources/static/js/util/windowLoad.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
  blockboard/src/test/java/com/board/project/blockboard/ModuleTest.java
Labels: bug, improvement

#216 알람 스크롤 페이징 완료
  blockboard/src/main/java/com/board/project/blockboard/common/config/WebConfig.java
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/controller/AlarmController.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/AlarmMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/AlarmService.java
  blockboard/src/main/resources/mybatis/mapper/AlarmMapper.xml
  blockboard/src/main/resources/static/css/alarmstyle.css
  blockboard/src/main/resources/static/js/ajax/alarmAjax.js
  blockboard/src/main/resources/static/js/data/const.js
  blockboard/src/main/resources/static/js/event/alarmEvent.js
  blockboard/src/main/resources/static/js/updateUI/alarmUI.js
  blockboard/src/main/resources/static/js/util/windowLoad.js
Labels: improvement

#215 기독 스크롤 페이징
  blockboard/src/main/java/com/board/project/blockboard/common/constant/ConstantData.java
  blockboard/src/main/java/com/board/project/blockboard/controller/ViewRecordController.java
  blockboard/src/main/java/com/board/project/blockboard/mapper/ViewRecordMapper.java
  blockboard/src/main/java/com/board/project/blockboard/service/ViewRecordService.java
  blockboard/src/main/resources/mybatis/mapper/ViewRecordMapper.xml
  blockboard/src/main/resources/static/css/boardstyle.css
  blockboard/src/main/resources/static/js/ajax/viewRecordAjax.js
  blockboard/src/main/resources/static/js/event/viewRecordEvent.js
  blockboard/src/main/resources/static/js/updateUI/viewRecordUI.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
  blockboard/강혜원.PNG
  blockboard/권은비.PNG
  blockboard/김채원.PNG
  blockboard/미와야키사쿠라.PNG
  blockboard/아부키나코.PNG
  blockboard/안유진.PNG
  blockboard/이채연.PNG
  blockboard/장원영.PNG
  blockboard/조유리.PNG
  blockboard/최예나.PNG
  blockboard/혼다히토미.PNG
Labels: improvement

#217 기독 오류
  Database/table_create.sql
  Database/user.sql
  blockboard/src/main/java/com/board/project/blockboard/service/AmazonRekognitionService.java
  blockboard/src/main/resources/static/js/ajax/viewRecordAjax.js
  blockboard/src/main/resources/static/js/event/viewRecordEvent.js
  blockboard/src/main/resources/static/js/updateUI/viewRecordUI.js
  blockboard/김남주.PNG
  blockboard/디오.jfif
  blockboard/랩몬스터.jfif
  blockboard/레이.jpg
  blockboard/로제.jfif
  blockboard/리사.PNG
  blockboard/백현.jfif
  blockboard/서현.jpg
  blockboard/세훈.jpg
  blockboard/손나은.PNG
  blockboard/수영.jpg
  blockboard/수호.jpg
  blockboard/슈가.jpg
  blockboard/시우민.jpg
  blockboard/써니.jpg
  blockboard/오하영.PNG
  blockboard/유리.jpg
  blockboard/윤아.jfif
  blockboard/정국.jfif
  blockboard/정은지.PNG
  blockboard/제니.jpg
  blockboard/제시카.jfif
  blockboard/제이홉.jpg
  blockboard/지민.jpg
  blockboard/지수.jpg
  blockboard/진.jpg
  blockboard/찬열.jpg
  blockboard/첸.jpg
  blockboard/카이.jpg
  blockboard/티파니.jpg
  blockboard/효연.jpg
Labels: improvement

#218 CSRF 적용 & 알람댓글달기 오류 수정
  blockboard/src/main/java/com/board/project/blockboard/common/interceptor/JwtInterceptor.java
  blockboard/src/main/java/com/board/project/blockboard/common/util/CookieUtils.java
  blockboard/src/main/java/com/board/project/blockboard/controller/UserController.java
  blockboard/src/main/resources/static/js/event/userEvent.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/webapp/WEB-INF/views/boards.jsp
  blockboard/src/main/webapp/WEB-INF/views/login.jsp
Labels: bug, enhancement, improvement

#221 알람 주기적 업데이트
  blockboard/src/main/java/com/board/project/blockboard/common/util/TagCheckUtils.java
  blockboard/src/main/java/com/board/project/blockboard/service/AlarmService.java
  blockboard/src/main/java/com/board/project/blockboard/service/CommentService.java
  blockboard/src/main/java/com/board/project/blockboard/service/ReplyService.java
  blockboard/src/main/resources/mybatis/mapper/AlarmMapper.xml
  blockboard/src/main/resources/static/js/ajax/alarmAjax.js
  blockboard/src/main/resources/static/js/updateUI/alarmUI.js
  blockboard/src/main/resources/static/js/util/handlebarsHelper.js
  blockboard/src/main/resources/static/js/util/windowLoad.js
Labels: improvement
